name:                morse
version:             0.1.0.0
github:              "willprice/morse"
license:             BSD3
author:              "Will Price"
maintainer:          "will.price94@gmail.com"
copyright:           "2018 Will Price"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/willprice/morse#readme>

dependencies:
- base >= 4.7 && < 5
- QuickCheck
- containers

library:
  source-dirs: src

executables:
  morse:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -Wall
    - -fwarn-tabs
    dependencies:
    - morse

tests:
  morse-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -Wall
    - -fno-warn-orphans
    dependencies:
    - morse
